-- ============================================================================
-- HELM calculation governance — Meridian Pharma Value Model v1.1
--
-- GENERATED FILE -- produced by scripts/generate-calculation-governance.mjs from
-- packages/propagation-engine/src/meridianValueModelV1_1.ts. Do not hand-edit.
--
-- Upserts the governance row of every v1.1 calculation: the nine v1 rows are
-- restated unchanged, and the four scenario calculations (order_quantity,
-- demand_coverage, unserved_demand, revenue_at_risk) are added. Metadata only:
-- no executable code reaches the database. Depends on the value-metric sync,
-- which registers the metrics these calculations write.
-- ============================================================================

INSERT INTO public.helm_calculations
  (id, org_id, key, version, name, description, rationale, owner, status,
   effective_from, output_metric_id, output_unit, scope_compatibility,
   definition_confidence, expression, inputs, is_system, metadata)
VALUES
  ('calc_expected_revenue@1.0.0', NULL, 'expected_revenue', '1.0.0', 'Expected Revenue', 'Probability-weighted revenue from an opportunity.', 'Commercial commitments are uncertain. Weighting the opportunity value by its probability gives the revenue the business can plan against, rather than the best case it can hope for.', 'Country GM Vietnam', 'ACTIVE', '2026-10-01', 'vm_expectedrevenue', 'currency', ARRAY['commercial', 'market']::text[], 1, 'opportunity_value × opportunity_probability', '[{"name":"opportunity_value","metricKey":"OpportunityValue","binding":{"kind":"SAME_SUBJECT"},"resolution":"SOURCE_POLICY_ONLY","required":true,"expectUnit":"currency","preference":null,"horizon":"current","allowCrossPeriod":false,"description":"The full value of the opportunity, before probability weighting."},{"name":"opportunity_probability","metricKey":"OpportunityProbability","binding":{"kind":"SAME_SUBJECT"},"resolution":"SOURCE_POLICY_ONLY","required":true,"expectUnit":"ratio","preference":null,"horizon":"current","allowCrossPeriod":false,"description":"Likelihood the opportunity closes, as a ratio between 0 and 1."}]'::jsonb, true, '{}'::jsonb),
  ('calc_demand_quantity@1.0.0', NULL, 'demand_quantity', '1.0.0', 'Demand Quantity', 'Probability-weighted expected unit demand implied by expected revenue.', 'Expected revenue has to become physical demand before supply can be planned. Dividing by the average selling price converts money into units. The result is deliberately fractional: 8.4 units is the expected value across outcomes, not a shipment. Rounding to a whole number is a commercial commitment decision, not a calculation, so this model does not do it.', 'Country GM Vietnam', 'ACTIVE', '2026-10-01', 'vm_demandquantity', 'units', ARRAY['commercial', 'market']::text[], 0.9, 'expected_revenue ÷ average_selling_price', '[{"name":"expected_revenue","metricKey":"ExpectedRevenue","binding":{"kind":"SAME_SUBJECT"},"resolution":"RUN_OUTPUT_IF_PLANNED","required":true,"expectUnit":"currency","preference":null,"horizon":"quarter","allowCrossPeriod":false,"description":"Probability-weighted revenue for this opportunity."},{"name":"average_selling_price","metricKey":"AverageSellingPrice","binding":{"kind":"RELATED_ENTITY","relationshipTypeKey":"SELLS","direction":"out"},"resolution":"SOURCE_POLICY_ONLY","required":true,"expectUnit":"currency","preference":"ASSUMPTION_ONLY","horizon":"current","allowCrossPeriod":false,"description":"Management assumption for realised price per unit of the product sold."}]'::jsonb, true, '{}'::jsonb),
  ('calc_inventory_requirement@1.0.0', NULL, 'inventory_requirement', '1.0.0', 'Inventory Requirement', 'Units of stock needed to serve expected demand.', 'MODEL v1: the requirement equals total demand exactly. There is no safety stock, no service-level buffer and no lead-time cover, because none of those policies is modelled yet. The arithmetic is trivial and honest; the confidence reflects that the MODEL is crude, not that the number is uncertain. Demand from EVERY opportunity selling the product is summed, which is what makes the pressure on a shared stock position a number rather than an observation about the graph.', 'Country GM Vietnam', 'ACTIVE', '2026-10-01', 'vm_inventoryrequirement', 'units', ARRAY['operations', 'commercial', 'resource']::text[], 0.8, 'Σ demand_quantity  (v1: no safety stock policy)', '[{"name":"demand_quantity","metricKey":"DemandQuantity","binding":{"kind":"RELATED_ENTITY","relationshipTypeKey":"SELLS","direction":"in","aggregate":true},"resolution":"RUN_OUTPUT_IF_PLANNED","required":true,"expectUnit":"units","preference":null,"horizon":"quarter","allowCrossPeriod":false,"description":"Expected unit demand from the opportunities selling this product."}]'::jsonb, true, '{}'::jsonb),
  ('calc_inventory_gap@1.0.0', NULL, 'inventory_gap', '1.0.0', 'Inventory Gap', 'Units of demand that cannot be served from available own stock.', 'The gap measures requirement against stock the business already controls. Distributor-held stock is deliberately excluded: reallocating it is a commercial decision with its own consequences, not automatic availability. Floored at zero, because surplus stock is a working-capital question, not a negative gap.', 'Country GM Vietnam', 'ACTIVE', '2026-10-01', 'vm_inventorygap', 'units', ARRAY['operations', 'commercial', 'resource']::text[], 0.9, 'max(inventory_requirement − available_inventory, 0)', '[{"name":"inventory_requirement","metricKey":"InventoryRequirement","binding":{"kind":"SAME_SUBJECT"},"resolution":"RUN_OUTPUT_IF_PLANNED","required":true,"expectUnit":"units","preference":null,"horizon":"quarter","allowCrossPeriod":false,"description":"Units needed to serve expected demand for this product."},{"name":"available_inventory","metricKey":"AvailableInventory","binding":{"kind":"RELATED_ENTITY","relationshipTypeKey":"POSITIONS","direction":"in","subjectFilter":{"attribute":"ownership","equals":"own"},"aggregate":true},"resolution":"SOURCE_POLICY_ONLY","required":true,"expectUnit":"units","preference":"ACTUALS_FIRST","horizon":"current","allowCrossPeriod":false,"description":"Units on hand at positions the business owns outright."}]'::jsonb, true, '{}'::jsonb),
  ('calc_working_capital@1.0.0', NULL, 'working_capital', '1.0.0', 'Working Capital Requirement', 'Capital tied up by holding the required inventory.', 'Inventory is capital before it is service. Valuing the requirement at unit cost shows what serving this demand ties up, which is the number that competes with every other use of cash. v1 values at cost and ignores payment terms. This is working capital for ONE product; the entity-level position a finance team reports is an aggregate across products that v1 deliberately does not attempt, which is why the calculation refuses to run on a finance subject rather than producing a number that looks like a balance-sheet figure and is not one.', 'Finance Director Vietnam', 'ACTIVE', '2026-10-01', 'vm_workingcapital', 'currency', ARRAY['operations', 'commercial', 'resource']::text[], 0.85, 'inventory_requirement × unit_cost', '[{"name":"inventory_requirement","metricKey":"InventoryRequirement","binding":{"kind":"SAME_SUBJECT"},"resolution":"RUN_OUTPUT_IF_PLANNED","required":true,"expectUnit":"units","preference":null,"horizon":"quarter","allowCrossPeriod":false,"description":"Units of stock the business needs to hold."},{"name":"unit_cost","metricKey":"UnitCost","binding":{"kind":"SAME_SUBJECT"},"resolution":"SOURCE_POLICY_ONLY","required":true,"expectUnit":"currency","preference":null,"horizon":"current","allowCrossPeriod":false,"description":"Landed cost of one unit of the product."}]'::jsonb, true, '{}'::jsonb),
  ('calc_cogs@1.0.0', NULL, 'cogs', '1.0.0', 'Cost of Goods Sold', 'Product cost of the units expected to be sold.', 'Separated from working capital on purpose: the same unit cost drives both, but COGS follows what is sold while working capital follows what is held. Keeping them as distinct calculations means a change in stock policy moves one and not the other.', 'Finance Director Vietnam', 'ACTIVE', '2026-10-01', 'vm_cogs', 'currency', ARRAY['commercial', 'market']::text[], 0.95, 'demand_quantity × unit_cost', '[{"name":"demand_quantity","metricKey":"DemandQuantity","binding":{"kind":"SAME_SUBJECT"},"resolution":"RUN_OUTPUT_IF_PLANNED","required":true,"expectUnit":"units","preference":null,"horizon":"quarter","allowCrossPeriod":false,"description":"Expected units sold under this opportunity."},{"name":"unit_cost","metricKey":"UnitCost","binding":{"kind":"RELATED_ENTITY","relationshipTypeKey":"SELLS","direction":"out"},"resolution":"SOURCE_POLICY_ONLY","required":true,"expectUnit":"currency","preference":null,"horizon":"current","allowCrossPeriod":false,"description":"Landed cost of one unit of the product being sold."}]'::jsonb, true, '{}'::jsonb),
  ('calc_gross_margin@1.0.0', NULL, 'gross_margin', '1.0.0', 'Gross Margin', 'Expected revenue less product cost and incremental fulfilment cost.', 'Margin is what survives after the cost of the goods and the cost of getting them there. Fulfilment cost is optional because most opportunities carry none; when expediting is on the table it becomes the visible price of protecting the deal. Deal-level only: an enterprise margin is a consolidation, not this formula summed.', 'Finance Director Vietnam', 'ACTIVE', '2026-10-01', 'vm_grossmargin', 'currency', ARRAY['commercial', 'market']::text[], 0.9, 'expected_revenue − cogs − fulfilment_cost', '[{"name":"expected_revenue","metricKey":"ExpectedRevenue","binding":{"kind":"SAME_SUBJECT"},"resolution":"RUN_OUTPUT_IF_PLANNED","required":true,"expectUnit":"currency","preference":null,"horizon":"quarter","allowCrossPeriod":false,"description":"Probability-weighted revenue for this opportunity."},{"name":"cogs","metricKey":"Cogs","binding":{"kind":"SAME_SUBJECT"},"resolution":"RUN_OUTPUT_IF_PLANNED","required":true,"expectUnit":"currency","preference":null,"horizon":"quarter","allowCrossPeriod":false,"description":"Product cost of the units expected to be sold."},{"name":"fulfilment_cost","metricKey":"Opex","binding":{"kind":"RELATED_ENTITY","relationshipTypeKey":"INCURS","direction":"out"},"resolution":"SOURCE_POLICY_ONLY","required":false,"expectUnit":"currency","preference":null,"horizon":"quarter","allowCrossPeriod":false,"description":"Incremental operating cost of fulfilling this opportunity, if any."}]'::jsonb, true, '{}'::jsonb),
  ('calc_gross_margin_pct@1.0.0', NULL, 'gross_margin_pct', '1.0.0', 'Gross Margin %', 'Gross margin as a percentage of expected revenue.', 'The percentage is what management steers by and what objectives are written against. Derived from the currency figures rather than stated separately, so the two can never disagree.', 'Finance Director Vietnam', 'ACTIVE', '2026-10-01', 'vm_grossmarginpct', 'percentage', ARRAY['commercial', 'market']::text[], 1, 'gross_margin ÷ expected_revenue × 100', '[{"name":"gross_margin","metricKey":"GrossMargin","binding":{"kind":"SAME_SUBJECT"},"resolution":"RUN_OUTPUT_IF_PLANNED","required":true,"expectUnit":"currency","preference":null,"horizon":"quarter","allowCrossPeriod":false,"description":"Gross margin in currency for this subject."},{"name":"expected_revenue","metricKey":"ExpectedRevenue","binding":{"kind":"SAME_SUBJECT"},"resolution":"RUN_OUTPUT_IF_PLANNED","required":true,"expectUnit":"currency","preference":null,"horizon":"quarter","allowCrossPeriod":false,"description":"Probability-weighted revenue the margin is measured against."}]'::jsonb, true, '{}'::jsonb),
  ('calc_cash_impact@1.0.0', NULL, 'cash_impact', '1.0.0', 'Cash Impact', 'Net cash effect of serving this demand over the horizon.', 'MODEL v1, deliberately simple: margin earned less capital tied up. It ignores payment terms, collection timing and tax. It is stated as a v1 cash model rather than dressed up as a cash-flow statement, because a model that looks more sophisticated than it is would be trusted more than it deserves.', 'Finance Director Vietnam', 'ACTIVE', '2026-10-01', 'vm_cashimpact', 'currency', ARRAY['commercial', 'market']::text[], 0.7, 'gross_margin − working_capital  (v1: ignores payment terms and timing)', '[{"name":"gross_margin","metricKey":"GrossMargin","binding":{"kind":"SAME_SUBJECT"},"resolution":"RUN_OUTPUT_IF_PLANNED","required":true,"expectUnit":"currency","preference":null,"horizon":"quarter","allowCrossPeriod":false,"description":"Gross margin expected from this opportunity."},{"name":"working_capital","metricKey":"WorkingCapital","binding":{"kind":"RELATED_ENTITY","relationshipTypeKey":"SELLS","direction":"out"},"resolution":"RUN_OUTPUT_IF_PLANNED","required":true,"expectUnit":"currency","preference":null,"horizon":"quarter","allowCrossPeriod":false,"description":"Capital tied up holding the inventory this demand requires."}]'::jsonb, true, '{}'::jsonb),
  ('calc_order_quantity@1.0.0', NULL, 'order_quantity', '1.0.0', 'Order Quantity', 'Units the business must deliver if the opportunity is won.', 'Feasibility is a question about what must ship, not about what is expected. Expected demand (8.4 units) is right for planning revenue and wrong for asking whether an order can be fulfilled: a won order ships 12 units or it is late. Valued at the same assumed selling price demand already uses, so the two cannot disagree about what a unit is worth. MODEL v1.1 assumes the whole order falls in the modelled period.', 'Country GM Vietnam', 'ACTIVE', '2026-10-01', 'vm_orderquantity', 'units', ARRAY['commercial', 'market']::text[], 0.9, 'opportunity_value ÷ average_selling_price', '[{"name":"opportunity_value","metricKey":"OpportunityValue","binding":{"kind":"SAME_SUBJECT"},"resolution":"SOURCE_POLICY_ONLY","required":true,"expectUnit":"currency","preference":null,"horizon":"current","allowCrossPeriod":false,"description":"The full value of the opportunity if it is won."},{"name":"average_selling_price","metricKey":"AverageSellingPrice","binding":{"kind":"RELATED_ENTITY","relationshipTypeKey":"SELLS","direction":"out"},"resolution":"SOURCE_POLICY_ONLY","required":true,"expectUnit":"currency","preference":"ASSUMPTION_ONLY","horizon":"current","allowCrossPeriod":false,"description":"Management assumption for realised price per unit of the product sold."}]'::jsonb, true, '{}'::jsonb),
  ('calc_demand_coverage@1.0.0', NULL, 'demand_coverage', '1.0.0', 'Demand Coverage', 'Share of the period requirement that own stock covers.', 'The ability to serve, measured the only way v1.1 can: own available stock against the requirement for the period, capped at the requirement because surplus stock does not serve more than all of the demand. This is a PROXY for service, not a service level — it ignores lead time, partial deliveries and the timing of demand within the period — and the metric is named so nobody mistakes it for the SLA.', 'Supply Chain Director Vietnam', 'ACTIVE', '2026-10-01', 'vm_demandcoverage', 'percentage', ARRAY['operations', 'commercial', 'resource']::text[], 0.7, 'min(available_inventory, inventory_requirement) ÷ inventory_requirement × 100', '[{"name":"inventory_requirement","metricKey":"InventoryRequirement","binding":{"kind":"SAME_SUBJECT"},"resolution":"RUN_OUTPUT_IF_PLANNED","required":true,"expectUnit":"units","preference":null,"horizon":"quarter","allowCrossPeriod":false,"description":"Units needed to serve expected demand for this product."},{"name":"available_inventory","metricKey":"AvailableInventory","binding":{"kind":"RELATED_ENTITY","relationshipTypeKey":"POSITIONS","direction":"in","subjectFilter":{"attribute":"ownership","equals":"own"},"aggregate":true},"resolution":"SOURCE_POLICY_ONLY","required":true,"expectUnit":"units","preference":"ACTUALS_FIRST","horizon":"current","allowCrossPeriod":false,"description":"Units on hand at positions the business owns outright."}]'::jsonb, true, '{}'::jsonb),
  ('calc_unserved_demand@1.0.0', NULL, 'unserved_demand', '1.0.0', 'Unserved Order Quantity', 'Units of a won order that the stock allocated to it would not cover.', 'Allocation is a management choice, so this calculation never makes one: it reads the allocation a person or a scenario stated and reports what that choice leaves uncovered. With no allocation stated it does not assume one — it blocks, because "nothing allocated" and "not yet decided" are different facts.', 'Country GM Vietnam', 'ACTIVE', '2026-10-01', 'vm_unserveddemand', 'units', ARRAY['commercial', 'market']::text[], 0.9, 'max(order_quantity − allocated_inventory, 0)', '[{"name":"order_quantity","metricKey":"OrderQuantity","binding":{"kind":"SAME_SUBJECT"},"resolution":"RUN_OUTPUT_IF_PLANNED","required":true,"expectUnit":"units","preference":null,"horizon":"quarter","allowCrossPeriod":false,"description":"Units that must ship if this opportunity is won."},{"name":"allocated_inventory","metricKey":"AllocatedInventory","binding":{"kind":"SAME_SUBJECT"},"resolution":"SOURCE_POLICY_ONLY","required":true,"expectUnit":"units","preference":null,"horizon":"quarter","allowCrossPeriod":false,"description":"Units of own stock committed to this opportunity for the period."}]'::jsonb, true, '{}'::jsonb),
  ('calc_revenue_at_risk@1.0.0', NULL, 'revenue_at_risk', '1.0.0', 'Revenue at Risk', 'Expected revenue attached to the part of an order that cannot be served.', 'If a third of an order cannot ship, a third of its expected revenue is exposed. MODEL v1.1 treats that exposure proportionally and as lost rather than deferred: it ignores late-delivery penalties, partial acceptance and substitution, none of which HELM has a basis for. Probability is inherited from expected revenue, never introduced here.', 'Finance Director Vietnam', 'ACTIVE', '2026-10-01', 'vm_revenueatrisk', 'currency', ARRAY['commercial', 'market']::text[], 0.6, 'expected_revenue × unserved_demand ÷ order_quantity', '[{"name":"expected_revenue","metricKey":"ExpectedRevenue","binding":{"kind":"SAME_SUBJECT"},"resolution":"RUN_OUTPUT_IF_PLANNED","required":true,"expectUnit":"currency","preference":null,"horizon":"quarter","allowCrossPeriod":false,"description":"Probability-weighted revenue for this opportunity."},{"name":"unserved_demand","metricKey":"UnservedDemand","binding":{"kind":"SAME_SUBJECT"},"resolution":"RUN_OUTPUT_IF_PLANNED","required":true,"expectUnit":"units","preference":null,"horizon":"quarter","allowCrossPeriod":false,"description":"Units of the order the allocated stock would not cover."},{"name":"order_quantity","metricKey":"OrderQuantity","binding":{"kind":"SAME_SUBJECT"},"resolution":"RUN_OUTPUT_IF_PLANNED","required":true,"expectUnit":"units","preference":null,"horizon":"quarter","allowCrossPeriod":false,"description":"Units that must ship if this opportunity is won."}]'::jsonb, true, '{}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  rationale = EXCLUDED.rationale,
  owner = EXCLUDED.owner,
  status = EXCLUDED.status,
  expression = EXCLUDED.expression,
  definition_confidence = EXCLUDED.definition_confidence,
  scope_compatibility = EXCLUDED.scope_compatibility,
  inputs = EXCLUDED.inputs,
  metadata = EXCLUDED.metadata
WHERE public.helm_calculations.org_id IS NULL;
